### ISSUE TITLE
Load modules from server into client instead of require

### ISSUE THREAD

**Issue by hle35** [CosyVerif/library#102]

**Comment by saucisson** [comment]
The code of `cosy.cli` is too complex. It is a nice prototype, but will not be maintainable. The following proposal tries to fix maintainability.

* do not load any module (even `cosy.loader`) outside of `Cli.configure` and `Cli.start`;
* in `Cli.configure`, do not use any module; try to read the `--server` option in arguments and in file `$HOME/.cosy/cli.data` (read it without call to `cosy.file`); then require `cosy.loader.cli` and then write data to the file;
* in `Cli.start`, load all required modules **after** call to `Cli.configure`.
* in `cosy.loader.cli`, also do not use configuration for packages path, but use instead a hard-coded path `$HOME/.cosy/lua/<server base64>`;
* do not forget the `<server base64>` part in the above path to distinguish files downloaded from different servers;
* and maybe some other things...


These changes avoid to reload modules.
