### ISSUE TITLE
Modify install to enable a path to store config alternative to default path ~/.cosy/

### ISSUE THREAD

**Issue by hle35** [CosyVerif/library#115]
It seems that sometimes NFS causes problems to access to ~/.cosy/  config files.
Currently, config is stored in ~/.cosy/  even when install is called with a different --prefix path.

**Comment by saucisson** [comment]
Maybe we can use the same technique as `LUA_PATH`: set a variable `COSY_CONFIG` containing a list of paths to search. It is easy to do and allows configuration from the `cosy` shell script.
