### ISSUE TITLE
Add a test to tests/user.sh to check that the path to cosy  was passed as an argument

### ISSUE THREAD

**Issue by hle35** [CosyVerif/library#125]

**Comment by hle35** [comment]
#! /bin/bash
if [ -z "$1" ]; then
    echo "usage: $0 path_to_bin_cosy"
    echo "ex: $0 /home/cosy/bin/cosy"
    exit
##  read -p "Enter pathname of cosy" cosy
else
    cosy="$1"
fi



passwords=$(mktemp)
echo "password" >> "${passwords}"
echo "password" >> "${passwords}"

#echo "Stopping daemon:"
#"${cosy}" daemon:stop --force
#echo "Stopping server:"
#"${cosy}" server:stop  --force
#echo "Starting server:"
#"${cosy}" server:start --force --clean
echo "Printing available methods:"
"${cosy}"
echo "Server information:"
"${cosy}" server:information
cosy@cosy:~/cosy/library/bin$

**Comment by saucisson** [comment]
Fixed by #126
