### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by achouba** [CosyVerif/library#2]
1- Code samples to make callbacks of javascript websockets in Lua
2- Make a separate Http folder 
3- Install demo server with automatic pull (may be using github webhooks with php https://jonathanstark.com/blog/deploying-code-automatically-with-github-webhooks )

**Comment by saucisson** [comment]
Please make three different issues ;-)

**Comment by achouba** [comment]
C'est fait, ça ne te dérange pas d’écrire en anglais?

2015-04-23 14:51 GMT+02:00 Alban Linard <notifications@github.com>:
