### ISSUE TITLE
infinite loop in repository

### ISSUE THREAD

**Issue by Alexis-Martin** [CosyVerif/library#24]
local Repository = require "cosy.repository"
    repository = Repository.new()
    Repository.options (repository).create = function () return {} end
    Repository.options (repository).import = function () return {} end

    local _ = Repository.placeholder(repository)

    repository.type1 = {
      type1_type = {
      
        set_type = {},
        
        set = {
          object_1 = {
            [Repository.refines] = {
		          _.type1_type.set_type,
		        },
		      },
        }
      
      },
    }

    repository.type2 = {
	    [Repository.depends] = {
		    repository.type1,
	    },
      
      [Repository.refines] = {
		    _.type1_type
	    },

      set = {
        object_2 = {
          [Repository.refines] = {
	          _.type1_type.set_type,
	        },
	      },
      },
      
    }

    do
      local set = repository.type2.set

      for k,v in Repository.iterate(set) do
        print(k, set[k])
      end
    end

the result is : 

     object_2	/type2/.set.object_2
     object_1	/type2/.set.object_1
     -infinite loop-

**Comment by saucisson** [comment]
I have rewritten this library as a standalone project : [lua-layeredata](https://github.com/saucisson/lua-layeredata). Your example has been updated and added in `test/alexismartin.lua`. It seems to work.

Main changes are:

* the repository disappeared
* the ambiguous `_` token has been replaced by `Proxy.placeholder` (a constant) and access to `nil` key in tables (for reading a value).

The listing is now:

````lua
$ luajit test/alexismartin.lua 
... (dump layers) ...
set	<"layer2"> ["type2"] ["set"]
object_2	<"layer2"> ["type2"] ["set"] ["object_2"]
object_1	<"layer2"> ["type2"] ["set"] ["object_1"]
````
