### ISSUE TITLE
integrate recaptcha

### ISSUE THREAD

**Issue by achouba** [CosyVerif/library#26]
Can you make following changes?
1- ad to method-conf captcha a config with 2 keys: "public" and "private" to store recaptcha keys
2- pass remote ip from websocket connection  to create_user method
3- create_user method will have two additional parameters: "recaptcha_challenge_field and" "recaptcha_response_field"
3- adapt the function "ReCaptcha:verify" in this file https://github.com/yuri/lua-recaptcha/blob/master/lua/recaptcha.lua to work with cosy library (http, ...)

**Comment by saucisson** [comment]
Wrong id for closing :-(

**Comment by saucisson** [comment]
Still cannot find a way to get remote IP address :-(

**Comment by saucisson** [comment]
Done in f2e4bfada059f97299f7b6cd75dae172ae241611
