### ISSUE TITLE
Update user: Picture

### ISSUE THREAD

**Issue by achouba** [CosyVerif/library#30]
It does not work, the file is posted with additional lines:

------WebKitFormBoundaryS1clsazJaNv9o1B4
Content-Disposition: form-data; name="cosy-avatar"; filename="avatar2.png"
Content-Type: image/png

(Binary DATA)
------WebKitFormBoundaryS1clsazJaNv9o1B4

**Comment by saucisson** [comment]
Is it the data stored instead of the image?

**Comment by saucisson** [comment]
Waiting for the push of @achouba to upgrade commands.
