### ISSUE TITLE
bcrypt issue

### ISSUE THREAD

**Issue by achouba** [CosyVerif/library#6]
I have updated the code with latest commits and I got this error:

Error: do local _="/home/sofiane/.luarocks/share/lua/5.1/hotswap.lua:92: /home/sofiane/.luarocks/lib/lua/5.1/bcrypt.so: undefined symbol: clock_gettime";return _;end => stack traceback:
	./cosy/methods.lua:578: in function <./cosy/methods.lua:576>
	[C]: in function 'error'
	/home/sofiane/.luarocks/share/lua/5.1/hotswap.lua:92: in function 'hotswap'
	./cosy/password.lua:10: in function 'compute_rounds'
	./cosy/password.lua:48: in function 'f'
	/home/sofiane/.luarocks/share/lua/5.1/hotswap.lua:94: in function '__index'
	./cosy/methods.lua:177: in function 'f'
	./cosy/methods.lua:573: in function <./cosy/methods.lua:571>
	[C]: in function 'xpcall'
	./cosy/methods.lua:571: in function 'method'
	cosy/server.lua:104: in function 'request'
	cosy/server.lua:123: in function 'get'
	cosy/server.lua:223: in function <cosy/server.lua:220>
	[C]: in function 'pcall'
	cosy/server.lua:220: in function 'f'
	/home/sofiane/.luarocks/share/lua/5.1/coroutine/make.lua:54: in function </home/sofiane/.luarocks/share/lua/5.1/coroutine/make.lua:53>

**Comment by saucisson** [comment]
Please try `luarocks install bcrypt` to upgrade the `bcrypt` dependency. It may require to also `luarocks install --only-deps cosyverif`, as it contains the dependecy to `bcrypt` with a version specifier that changed.

**Comment by saucisson** [comment]
Seems to work now, closing.
